platform :ios,’8.0’

#定义要安装的包
def pods
    pod 'MJRefresh', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'AFNetworking'
    pod 'Masonry'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMengUShare/UI’
    # 集成微信(精简版0.2M)
    pod 'UMengUShare/Social/ReducedWeChat'
    # 集成QQ(精简版0.5M)
    pod 'UMengUShare/Social/ReducedQQ'
    # 集成新浪微博(精简版1M)
    pod 'UMengUShare/Social/ReducedSina'
    # 集成邮件
    pod 'UMengUShare/Social/Email'
    # 集成短信
    pod 'UMengUShare/Social/SMS'
    # 加入IDFA获取
    pod 'UMengUShare/Plugin/IDFA'
    # 存储到钥匙串
    pod 'SSKeychain'

end

#创建targets
targetsArray = ['VencentDeepPockets','VencentDeepPockets_release','VDPTodayExtension']

#循环加载包
targetsArray.each do |t|
   target t do
   pods
   end
end

#* 网络通信模块(AFURLSessionManager、AFHTTPSessionManger)
#* 网络状态监听模块(Reachability)
#* 网络通信安全策略模块(Security)
#* 网络通信信息序列化/反序列化模块(Serialization)
#* 对于iOS UIKit库的扩展(UIKit)
