platform :ios,’8.0’

#定义要安装的包
def pods
    pod 'MJRefresh', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMengUShare/UI’
    # 集成微信(精简版0.2M)
    pod 'UMengUShare/Social/ReducedWeChat'
    # 集成QQ(精简版0.5M)
    pod 'UMengUShare/Social/ReducedQQ'
    # 集成新浪微博(精简版1M)
    pod 'UMengUShare/Social/ReducedSina'
    # 集成邮件
    pod 'UMengUShare/Social/Email'
    # 集成短信
    pod 'UMengUShare/Social/SMS'
    # 加入IDFA获取
    pod 'UMengUShare/Plugin/IDFA'

end

#创建targets
targetsArray = ['VencentDeepPockets','VencentDeepPockets_release','VDPTodayExtension']

#循环加载包
targetsArray.each do |t|
   target t do
   pods
   end
end

